export const mockProducts = [
  {
    key: '1',
    image: 'https://example.com/toner.jpg',
    productName: 'Nước Hoa Hồng',
    price: '200,000',
    category: 'Skin Care',
    brand: 'Simple',
    description: 'Purifies and soothes for toned and calm skin',
    status: 'Active',
  },
  {
    key: '2',
    image: 'https://example.com/cleanser.jpg',
    productName: 'Sữa Rửa Mặt',
    price: '150,000',
    category: 'Skin Care',
    brand: 'Simple',
    description: 'Gentle facial cleanser for all skin types',
    status: 'Active',
  },
  {
    key: '3',
    image: 'https://example.com/sunscreen.jpg',
    productName: 'Kem Chống Nắng',
    price: '350,000',
    category: 'Sun Care',
    brand: 'La Roche-Posay',
    description: 'SPF 50+ PA++++ for daily sun protection',
    status: 'Active',
  },
  {
    key: '4',
    image: 'https://example.com/serum.jpg',
    productName: 'Serum Vitamin C',
    price: '450,000',
    category: 'Skin Care',
    brand: 'The Ordinary',
    description: 'Brightening and anti-aging serum with 10% Vitamin C',
    status: 'Inactive',
  },
  {
    key: '5',
    image: 'https://example.com/moisturizer.jpg',
    productName: 'Kem Dưỡng Ẩm',
    price: '280,000',
    category: 'Skin Care',
    brand: 'Cerave',
    description: 'Hydrating moisturizer with ceramides and hyaluronic acid',
    status: 'Active',
  }
]; 